-- MySQL Script generated by MySQL Workbench
-- Wed Aug 15 11:36:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EDBNP
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EDBNP` ;

-- -----------------------------------------------------
-- Schema EDBNP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EDBNP` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `EDBNP` ;

-- -----------------------------------------------------
-- Table `EDBNP`.`Molecule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EDBNP`.`Molecule` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EDBNP`.`Molecule` (
  `uniqueMID` VARCHAR(50) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `SMILES` VARCHAR(45) NULL,
  `InChi` VARCHAR(45) NULL,
  `InChiKey` VARCHAR(45) NULL,
  `isANP` TINYINT NULL DEFAULT 0,
  `sdf_file_path` VARCHAR(100) NULL,
  `creation_date` DATETIME NULL,
  `last_modified` DATETIME NULL,
  `level_of_curation` VARCHAR(45) NULL COMMENT '\n\nNeed an enum!\n\nThe various levels will need to be defined:\n- manual validation?\n- from an other database ?\n- from several databases?\n- from littérature? = AI-curated',
  PRIMARY KEY (`uniqueMID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EDBNP`.`Organism`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EDBNP`.`Organism` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EDBNP`.`Organism` (
  `taxId` INT NOT NULL,
  `CommonName` VARCHAR(45) NULL,
  `genus` VARCHAR(45) NULL,
  PRIMARY KEY (`taxId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EDBNP`.`Enzyme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EDBNP`.`Enzyme` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EDBNP`.`Enzyme` (
  `PBID` VARCHAR(10) NOT NULL,
  `EnzymeName` VARCHAR(45) NULL DEFAULT NULL,
  `Enzymecol` VARCHAR(45) NULL,
  `taxId` INT NULL,
  PRIMARY KEY (`PBID`),
  CONSTRAINT `tacId`
    FOREIGN KEY (`taxId`)
    REFERENCES `EDBNP`.`Organism` (`taxId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `tacId_idx` ON `EDBNP`.`Enzyme` (`taxId` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EDBNP`.`PB_EC_CPD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EDBNP`.`PB_EC_CPD` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EDBNP`.`PB_EC_CPD` (
  `PBID` VARCHAR(10) NOT NULL,
  `EC_id` VARCHAR(45) NULL,
  CONSTRAINT `PBID`
    FOREIGN KEY (`PBID`)
    REFERENCES `EDBNP`.`Enzyme` (`PBID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `1` USING BTREE ON `EDBNP`.`PB_EC_CPD` (`PBID` ASC, `EC_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EDBNP`.`Reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EDBNP`.`Reaction` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EDBNP`.`Reaction` (
  `ReactionId` VARCHAR(20) NOT NULL,
  `ReactionEquation` VARCHAR(500) NULL,
  `isBalanced` TINYINT NULL,
  PRIMARY KEY (`ReactionId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EDBNP`.`Xref`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EDBNP`.`Xref` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EDBNP`.`Xref` (
  `xrefID` INT NOT NULL AUTO_INCREMENT,
  `idNP` VARCHAR(45) NULL,
  `idXref` VARCHAR(45) NULL,
  `xSource` VARCHAR(45) NULL,
  PRIMARY KEY (`xrefID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `u` ON `EDBNP`.`Xref` (`idNP` ASC, `idXref` ASC);

SHOW WARNINGS;
CREATE INDEX `s` USING BTREE ON `EDBNP`.`Xref` (`xSource` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EDBNP`.`Reaction_Enzyme_CPD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EDBNP`.`Reaction_Enzyme_CPD` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EDBNP`.`Reaction_Enzyme_CPD` (
  `ReactionId` VARCHAR(20) NOT NULL,
  `PBID` VARCHAR(10) NOT NULL,
  `cpdSource` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ReactionId`, `PBID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EDBNP`.`Spectra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EDBNP`.`Spectra` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EDBNP`.`Spectra` (
  `uniqueMolecularIdentifier` INT NOT NULL,
  `spectrumNMR` TEXT(1000) NULL,
  `spectrumMS` TEXT(1000) NULL,
  PRIMARY KEY (`uniqueMolecularIdentifier`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EDBNP`.`Publication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EDBNP`.`Publication` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EDBNP`.`Publication` (
  `DOI` VARCHAR(20) NOT NULL,
  `Title` VARCHAR(200) NULL,
  `year` INT NULL,
  `author_list` VARCHAR(500) NULL,
  `journal` VARCHAR(45) NULL,
  PRIMARY KEY (`DOI`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EDBNP`.`AtomSignature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EDBNP`.`AtomSignature` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EDBNP`.`AtomSignature` (
  `ASid` INT NOT NULL,
  `AtomSignature` VARCHAR(600) NULL,
  `height` INT NULL,
  `score` DOUBLE NULL,
  PRIMARY KEY (`ASid`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `index2` USING BTREE ON `EDBNP`.`AtomSignature` (`AtomSignature` ASC, `height` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `EDBNP`.`AtomSignature_Molecule_CPD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EDBNP`.`AtomSignature_Molecule_CPD` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EDBNP`.`AtomSignature_Molecule_CPD` (
  `ASid` INT NOT NULL,
  `uniqueMID` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ASid`, `uniqueMID`),
  CONSTRAINT `ASid`
    FOREIGN KEY (`ASid`)
    REFERENCES `EDBNP`.`AtomSignature` (`ASid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `uniqueMID`
    FOREIGN KEY (`uniqueMID`)
    REFERENCES `EDBNP`.`Molecule` (`uniqueMID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `uniqueMID_idx` ON `EDBNP`.`AtomSignature_Molecule_CPD` (`uniqueMID` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
